server:
  port: 8860

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8860/eureka/
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: server-eureka